# Form implementation generated from reading ui file 'd:\gitprojs\new-git\Time-Stack\Test\QtProgressbar\progressbar_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("QProgressBar {\n"
"border: 1px solid black;\n"
"text-align: top;\n"
"padding: 1px;\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"stop: 0 #fff,\n"
"stop: 0.4999 #eee,\n"
"stop: 0.5 #ddd,\n"
"stop: 1 #eee );\n"
"width: 15px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"stop: 0 #78d,\n"
"stop: 0.4999 #46a,\n"
"stop: 0.5 #45a,\n"
"stop: 1 #238 );\n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"border: 1px solid black;\n"
"}")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 60, 191, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(50, 120, 171, 121))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"                border: 1px solid black;\n"
"                text-align: top;\n"
"                padding: 1px;\n"
"                border-bottom-right-radius: 7px;\n"
"                border-bottom-left-radius: 7px;\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #fff,\n"
"                stop: 0.4999 #eee,\n"
"                stop: 0.5 #ddd,\n"
"                stop: 1 #eee );\n"
"                width: 15px;\n"
"                }\n"
"\n"
"        QProgressBar::chunk {\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #78d,\n"
"                stop: 0.4999 #46a,\n"
"                stop: 0.5 #45a,\n"
"                stop: 1 #238 );\n"
"                border-bottom-right-radius: 7px;\n"
"                border-bottom-left-radius: 7px;\n"
"                border: 1px solid black;\n"
"                }\n"
"        QProgressBar::groove:horizontal {\n"
"                border: 1px solid black;\n"
"                border-top-right-radius: 7px;\n"
"                border-top-left-radius: 7px;\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #fff,\n"
"                stop: 0.4999 #eee,\n"
"                stop: 0.5 #ddd,\n"
"                stop: 1 #eee );\n"
"                width: 15px;\n"
"                }\n"
"        QProgressBar::chunk:horizontal {\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #78d,\n"
"                stop: 0.4999 #46a,\n"
"                stop: 0.5 #45a,\n"
"                stop: 1 #238 );\n"
"                border-top-right-radius: 7px;\n"
"                border-top-left-radius: 7px;\n"
"                border: 1px solid black;\n"
"                }\n"
"        QProgressBar::groove:vertical {\n"
"                border: 1px solid black;\n"
"                border-bottom-right-radius: 7px;\n"
"                border-top-right-radius: 7px;\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #fff,\n"
"                stop: 0.4999 #eee,\n"
"                stop: 0.5 #ddd,\n"
"                stop: 1 #eee );\n"
"                width: 15px;\n"
"                }\n"
"        QProgressBar::chunk:vertical {\n"
"                background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0,\n"
"                stop: 0 #78d,\n"
"                stop: 0.4999 #46a,\n"
"                stop: 0.5 #45a,\n"
"                stop: 1 #238 );\n"
"                border-bottom-right-radius: 7px;\n"
"                border-top-right-radius: 7px;\n"
"                border: 1px solid black;\n"
"                }\n"
"\n"
"        ")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "START"))
