# Form implementation generated from reading ui file 'd:\gitprojs\new-git\Time-Stack\src\ui_files\settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(450, 560)
        settings.setMinimumSize(QtCore.QSize(450, 550))
        settings.setMaximumSize(QtCore.QSize(460, 560))
        font = QtGui.QFont()
        font.setPointSize(12)
        settings.setFont(font)
        settings.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.tab_widget = QtWidgets.QTabWidget(parent=settings)
        self.tab_widget.setGeometry(QtCore.QRect(10, 10, 430, 540))
        self.tab_widget.setMinimumSize(QtCore.QSize(430, 540))
        self.tab_widget.setMaximumSize(QtCore.QSize(430, 540))
        self.tab_widget.setObjectName("tab_widget")
        self.main_app = QtWidgets.QWidget()
        self.main_app.setObjectName("main_app")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.main_app)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_app_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_app_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.main_app_layout.setContentsMargins(20, 20, 20, 20)
        self.main_app_layout.setHorizontalSpacing(60)
        self.main_app_layout.setVerticalSpacing(20)
        self.main_app_layout.setObjectName("main_app_layout")
        self.theme_toggle_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.theme_toggle_label.setObjectName("theme_toggle_label")
        self.main_app_layout.addWidget(self.theme_toggle_label, 0, 0, 1, 1)
        self.close_icon_placeholder = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.close_icon_placeholder.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.close_icon_placeholder.setObjectName("close_icon_placeholder")
        self.main_app_layout.addWidget(self.close_icon_placeholder, 1, 2, 1, 1)
        self.close_to_tray_placeholder = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.close_to_tray_placeholder.setObjectName("close_to_tray_placeholder")
        self.main_app_layout.addWidget(self.close_to_tray_placeholder, 1, 1, 1, 1)
        self.theme_toggle_placeholder = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.theme_toggle_placeholder.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.theme_toggle_placeholder.setStyleSheet("")
        self.theme_toggle_placeholder.setObjectName("theme_toggle_placeholder")
        self.main_app_layout.addWidget(self.theme_toggle_placeholder, 0, 1, 1, 1)
        self.close_to_tray_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.close_to_tray_label.setObjectName("close_to_tray_label")
        self.main_app_layout.addWidget(self.close_to_tray_label, 1, 0, 1, 1)
        self.theme_icon_placeholder = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.theme_icon_placeholder.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.theme_icon_placeholder.setObjectName("theme_icon_placeholder")
        self.main_app_layout.addWidget(self.theme_icon_placeholder, 0, 2, 1, 1)
        self.main_app_layout.setRowStretch(0, 10)
        self.tab_widget.addTab(self.main_app, "")
        self.others = QtWidgets.QWidget()
        self.others.setObjectName("others")
        self.tab_widget.addTab(self.others, "")

        self.retranslateUi(settings)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Form"))
        self.theme_toggle_label.setText(_translate("settings", "TOGGLE THEME"))
        self.close_icon_placeholder.setText(_translate("settings", "theme_icon"))
        self.close_to_tray_label.setText(_translate("settings", "CLOSE TO TRAY"))
        self.theme_icon_placeholder.setText(_translate("settings", "theme_icon"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.main_app), _translate("settings", "Main App"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.others), _translate("settings", "Others"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings = QtWidgets.QWidget()
    ui = Ui_settings()
    ui.setupUi(settings)
    settings.show()
    sys.exit(app.exec())
