# Form implementation generated from reading ui file 'd:\gitprojs\new-git\Time-Stack\src\ui_files\stack_space.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_stack_space(object):
    def setupUi(self, stack_space):
        stack_space.setObjectName("stack_space")
        stack_space.resize(320, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(stack_space.sizePolicy().hasHeightForWidth())
        stack_space.setSizePolicy(sizePolicy)
        stack_space.setMinimumSize(QtCore.QSize(320, 180))
        stack_space.setMaximumSize(QtCore.QSize(320, 900))
        self.stack_area_scrollable = QtWidgets.QScrollArea(parent=stack_space)
        self.stack_area_scrollable.setGeometry(QtCore.QRect(10, 120, 301, 491))
        self.stack_area_scrollable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.stack_area_scrollable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.stack_area_scrollable.setWidgetResizable(True)
        self.stack_area_scrollable.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignTop)
        self.stack_area_scrollable.setObjectName("stack_area_scrollable")
        self.stack_dump = QtWidgets.QWidget()
        self.stack_dump.setGeometry(QtCore.QRect(0, 0, 282, 489))
        self.stack_dump.setObjectName("stack_dump")
        self.stack_area_scrollable.setWidget(self.stack_dump)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=stack_space)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.btn_layout_h = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.btn_layout_h.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.btn_layout_h.setContentsMargins(5, 5, 5, 5)
        self.btn_layout_h.setSpacing(4)
        self.btn_layout_h.setObjectName("btn_layout_h")
        self.add_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.add_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.add_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.add_btn.setObjectName("add_btn")
        self.btn_layout_h.addWidget(self.add_btn)
        self.settings_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.settings_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.settings_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.settings_btn.setObjectName("settings_btn")
        self.btn_layout_h.addWidget(self.settings_btn)
        self.extra_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.extra_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.extra_btn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.extra_btn.setObjectName("extra_btn")
        self.btn_layout_h.addWidget(self.extra_btn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=stack_space)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 301, 70))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.btn_layout_h_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.btn_layout_h_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.btn_layout_h_2.setContentsMargins(5, 5, 5, 5)
        self.btn_layout_h_2.setSpacing(4)
        self.btn_layout_h_2.setObjectName("btn_layout_h_2")
        self.start_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.start_btn.setMinimumSize(QtCore.QSize(60, 30))
        self.start_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.start_btn.setText("")
        self.start_btn.setObjectName("start_btn")
        self.btn_layout_h_2.addWidget(self.start_btn)
        self.pause_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.pause_btn.setMinimumSize(QtCore.QSize(60, 30))
        self.pause_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.pause_btn.setText("")
        self.pause_btn.setObjectName("pause_btn")
        self.btn_layout_h_2.addWidget(self.pause_btn)
        self.remove_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.remove_btn.setMinimumSize(QtCore.QSize(60, 30))
        self.remove_btn.setMaximumSize(QtCore.QSize(60, 30))
        self.remove_btn.setText("")
        self.remove_btn.setObjectName("remove_btn")
        self.btn_layout_h_2.addWidget(self.remove_btn)

        self.retranslateUi(stack_space)
        QtCore.QMetaObject.connectSlotsByName(stack_space)

    def retranslateUi(self, stack_space):
        _translate = QtCore.QCoreApplication.translate
        stack_space.setWindowTitle(_translate("stack_space", "STACK SPACE"))
        self.add_btn.setText(_translate("stack_space", "Add"))
        self.settings_btn.setText(_translate("stack_space", "Settings"))
        self.extra_btn.setText(_translate("stack_space", "Extra"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stack_space = QtWidgets.QWidget()
    ui = Ui_stack_space()
    ui.setupUi(stack_space)
    stack_space.show()
    sys.exit(app.exec())
