# Form implementation generated from reading ui file 'd:\gitprojs\new-git\Time-Stack\src\ui_files\time_stack.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 920)
        MainWindow.setMinimumSize(QtCore.QSize(700, 920))
        MainWindow.setMaximumSize(QtCore.QSize(700, 920))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 900))
        self.centralwidget.setMaximumSize(QtCore.QSize(700, 900))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 690, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab_widget = QtWidgets.QTabWidget(parent=self.verticalLayoutWidget)
        self.main_tab_widget.setMinimumSize(QtCore.QSize(650, 700))
        self.main_tab_widget.setMaximumSize(QtCore.QSize(650, 700))
        self.main_tab_widget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.main_tab_widget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.main_tab_widget.setMovable(True)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.addstack = QtWidgets.QWidget()
        self.addstack.setMinimumSize(QtCore.QSize(620, 694))
        self.addstack.setMaximumSize(QtCore.QSize(620, 694))
        self.addstack.setObjectName("addstack")
        self.main_tab_widget.addTab(self.addstack, "")
        self.stack_space = QtWidgets.QWidget()
        self.stack_space.setMinimumSize(QtCore.QSize(620, 700))
        self.stack_space.setMaximumSize(QtCore.QSize(620, 700))
        self.stack_space.setObjectName("stack_space")
        self.main_tab_widget.addTab(self.stack_space, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setMinimumSize(QtCore.QSize(620, 694))
        self.settings.setMaximumSize(QtCore.QSize(620, 694))
        self.settings.setObjectName("settings")
        self.main_tab_widget.addTab(self.settings, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.main_tab_widget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.main_tab_widget)
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(570, 10, 130, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.minimize_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.minimize_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_2.addWidget(self.minimize_btn)
        self.close_btn = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.close_btn.setMinimumSize(QtCore.QSize(50, 20))
        self.close_btn.setMaximumSize(QtCore.QSize(50, 20))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.logo_placeholder = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_placeholder.setGeometry(QtCore.QRect(60, 40, 490, 120))
        self.logo_placeholder.setMinimumSize(QtCore.QSize(490, 120))
        self.logo_placeholder.setMaximumSize(QtCore.QSize(490, 120))
        self.logo_placeholder.setObjectName("logo_placeholder")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.addstack), _translate("MainWindow", "Add Stack"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.stack_space), _translate("MainWindow", "Stack Space"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.settings), _translate("MainWindow", "Settings"))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        self.minimize_btn.setText(_translate("MainWindow", "Minimize"))
        self.close_btn.setText(_translate("MainWindow", "Close"))
        self.logo_placeholder.setText(_translate("MainWindow", "logo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
