# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TimeStackServer(object):
    '''
    Generated by PyQt6 UI code generator 6.4.1
    '''
    def setupUi(self, TimeStackServer):
        TimeStackServer.setObjectName("TimeStackServer")
        TimeStackServer.resize(544, 373)
        self.centralwidget = QtWidgets.QWidget(parent=TimeStackServer)
        self.centralwidget.setObjectName("centralwidget")
        self.message_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.message_field.setGeometry(QtCore.QRect(160, 45, 161, 21))
        self.message_field.setObjectName("message_field")
        self.submit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(340, 45, 75, 23))
        self.submit_btn.setObjectName("submit_btn")
        self.data_dump_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.data_dump_label.setGeometry(QtCore.QRect(70, 110, 81, 16))
        self.data_dump_label.setObjectName("data_dump_label")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 140, 481, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.response_label = QtWidgets.QLabel(
            parent=self.scrollAreaWidgetContents)
        self.response_label.setText("")
        self.response_label.setObjectName("response_label")
        self.verticalLayout.addWidget(self.response_label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.message_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.message_label.setGeometry(QtCore.QRect(50, 40, 101, 31))
        self.message_label.setObjectName("message_label")
        self.refresh_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_btn.setGeometry(QtCore.QRect(140, 110, 75, 23))
        self.refresh_btn.setObjectName("refresh_btn")
        TimeStackServer.setCentralWidget(self.centralwidget)

        self.retranslateUi(TimeStackServer)
        QtCore.QMetaObject.connectSlotsByName(TimeStackServer)

    def retranslateUi(self, TimeStackServer):
        _translate = QtCore.QCoreApplication.translate
        TimeStackServer.setWindowTitle(_translate(
            "TimeStackServer", "Time Stack Server"))
        self.submit_btn.setText(_translate("TimeStackServer", "Submit!"))
        self.data_dump_label.setText(
            _translate("TimeStackServer", "Data-Dump"))
        self.message_label.setText(_translate(
            "TimeStackServer", "Enter your message"))
        self.refresh_btn.setText(_translate("TimeStackServer", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimeStackServer = QtWidgets.QMainWindow()
    ui = Ui_TimeStackServer()
    ui.setupUi(TimeStackServer)
    TimeStackServer.show()
    sys.exit(app.exec())
